---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Vishal-Nagpure/application-config.git
          search-paths:
            - 'station*'
          #username:
          #password:

